apiVersion: apps/v1
kind: Deployment 
metadata:
  name: usermgmt-microservice
  labels:
    app: usermgmt-restapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usermgmt-restapp
  template:  
    metadata:
      labels: 
        app: usermgmt-restapp
    spec:
      initContainers:
      - name: init-myservice
        image: busybox:1.35
        command: ['sh', '-c']
        args:
          - |
            echo "Aguardando MySQL estar pronto..."
            until nc -z mysql 3306; do
              echo "MySQL não está pronto ainda, aguardando..."
              sleep 2
            done
            echo "MySQL está pronto!"
      containers:
        - name: usermgmt-restapp
          image: 1234samue/aula:user-management-api-1.0.0
          ports: 
            - containerPort: 3000
              name: http
          env:
            - name: DB_HOST
              value: "mysql"            
            - name: DB_PORT
              value: "3306"            
            - name: DB_NAME
              value: "usermgmt"            
            - name: DB_USER
              value: "root"            
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-db-password
                  key: db-password
            - name: PORT
              value: "3000"
