apiVersion: apps/v1
kind: Deployment 
metadata:
  name: usermgmt-microservice
  labels:
    app: usermgmt-restapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: usermgmt-restapp
  template:  
    metadata:
      labels: 
        app: usermgmt-restapp
    spec:
      containers:
        - name: usermgmt-restapp
          image: 1234samue/aula:user-management-api-1.0.0
          ports: 
            - containerPort: 3000
              name: http
          env:
            - name: DB_HOST
              value: "mysql"            
            - name: DB_PORT
              value: "3306"            
            - name: DB_NAME
              value: "usermgmt"            
            - name: DB_USER
              value: "root"            
            - name: DB_PASSWORD
              value: "dbpassword11"
            - name: PORT
              value: "3000"
