apiVersion: v1
kind: Service
metadata:
  name: user-management-api-nodeport
  labels:
    app: user-management-api
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: user-management-api
