apiVersion: v1
kind: Service
metadata:
  name: user-management-api-service
  labels:
    app: user-management-api
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: user-management-api
