apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp2-rs  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp2
  template: 
    metadata: # Dictionary
      name: myapp2-pod
      labels: # Dictionary 
        app: myapp2         
    spec:
      containers: # List
        - name: myapp2-container
          image: 1234samue/aula:kubenginx-1.0.0
          ports:
            - containerPort: 80


    