apiVersion: v1 # String
kind: Pod  # String
metadata: # Dictionary
  name: myapp-pod
  labels: # Dictionary 
    app: myapp         
spec:
  containers: # List
    - name: myapp
      image: 1234samue/aula:kubenginx-1.0.0
      ports:
        - containerPort: 80


    